export const events = [
  {
    title: "Event 1",
    date: 10,
    month: "June",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
    location: "Location 1",
  },
  {
    title: "Event 2",
    date: 15,
    month: "July",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    location: "Location 2",
  },
  {
    title: "Event 3",
    date: 20,
    month: "August",
    startTime: "6:30 PM",
    endTime: "8:30 PM",
    location: "Location 3",
  },
  {
    title: "Event 4",
    date: 5,
    month: "September",
    startTime: "9:00 AM",
    endTime: "11:00 AM",
    location: "Location 4",
  },
  {
    title: "Event 5",
    date: 12,
    month: "October",
    startTime: "1:00 PM",
    endTime: "3:00 PM",
    location: "Location 5",
  },
  {
    title: "Event 6",
    date: 25,
    month: "November",
    startTime: "4:30 PM",
    endTime: "6:30 PM",
    location: "Location 6",
  },
  {
    title: "Event 7",
    date: 8,
    month: "December",
    startTime: "7:00 PM",
    endTime: "9:00 PM",
    location: "Location 7",
  },
  {
    title: "Event 8",
    date: 20,
    month: "January",
    startTime: "10:30 AM",
    endTime: "12:30 PM",
    location: "Location 8",
  },
];
